version: '3'

services:
  mongodb:
    image: 'mongo:6.0-focal'
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=accounts
    volumes:
      - 'mongodb_data:/data/db'
      - './mongo-init:/docker-entrypoint-initdb.d'
    networks:
      - mongodb_network

volumes:
  mongodb_data:
    driver: local

networks:
  mongodb_network:
    driver: bridge